sonar.projectKey=mirija-712_skillhub
sonar.organization=mirija-712
sonar.host.url=https://sonarcloud.io

sonar.sources=authentification_back/src/main,skillhub_back/app,skillhub_back/routes,skillhub_back/config,skillhub_front/src
sonar.tests=authentification_back/src/test,skillhub_back/tests,skillhub_front/src

sonar.java.binaries=authentification_back/target/classes
sonar.java.libraries=authentification_back/target/dependency/*.jar
sonar.coverage.jacoco.xmlReportPaths=authentification_back/target/site/jacoco/jacoco.xml

sonar.php.coverage.reportPaths=skillhub_back/reports/clover.xml
sonar.php.tests.reportPath=skillhub_back/reports/junit.xml
sonar.javascript.lcov.reportPaths=skillhub_front/coverage/lcov.info
sonar.typescript.lcov.reportPaths=skillhub_front/coverage/lcov.info

sonar.test.inclusions=**/*Test.java,**/tests/**/*.php,**/*.test.{js,jsx,ts,tsx},**/*.spec.{js,jsx,ts,tsx}
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/public/**,**/storage/**,**/bootstrap/cache/**,**/target/**
