sonar.projectKey=mirija-712_skillhub
sonar.organization=mirija-712
sonar.host.url=https://sonarcloud.io

sonar.sources=authentification_back/src/main,skillhub_back/app,skillhub_back/routes,skillhub_back/config
sonar.tests=authentification_back/src/test,skillhub_back/tests

sonar.java.binaries=authentification_back/target/classes
sonar.java.libraries=authentification_back/target/dependency/*.jar
sonar.coverage.jacoco.xmlReportPaths=authentification_back/target/site/jacoco/jacoco.xml

sonar.php.coverage.reportPaths=skillhub_back/reports/clover.xml
sonar.php.tests.reportPath=skillhub_back/reports/junit.xml

sonar.test.inclusions=**/*Test.java,**/tests/**/*.php
sonar.exclusions=**/vendor/**,**/storage/**,**/bootstrap/cache/**,**/target/**
sonar.coverage.exclusions=\
  authentification_back/src/main/java/**/dto/**,\
  authentification_back/src/main/java/**/entity/**,\
  authentification_back/src/main/java/**/exception/**,\
  authentification_back/src/main/java/**/config/**,\
  authentification_back/src/main/java/**/repository/**,\
  authentification_back/src/main/java/**/AuthentificationBackApplication.java,\
  skillhub_back/app/Models/**,\
  skillhub_back/config/**,\
  skillhub_back/routes/**
